### ISSUE TITLE
Do we need to add a new line at the bottom of Java files?

### ISSUE THREAD

**Issue by benediktkaiser** [woolgens-network/guides#20]
@ReaperMaga in TS and JS we add new lines at the bottom of files. Should we add to the java conventions to do this also. 

Thanks?

**Comment by benediktkaiser** [comment]
Generally this is an old convention that was implemented in C and has been passed down to most modern languages.
Source: https://thoughtbot.com/blog/no-newline-at-end-of-file, https://www.quora.com/Why-is-it-good-practice-to-add-a-newline-to-the-end-of-a-file

Even GitHub warns when there is no new line at the bottom of the file, which is why I personally do think we should enforce this convention.

**Comment by ReaperMaga** [comment]
We are working with a Compiled language the JVM does its work to optimize such things. I never actually had problems in my entire Java Career.

**Comment by benediktkaiser** [comment]
You won't ever face issues in modern languages, however I think it's just a nice convention to hold. (And I don't like the GitHub errors :P)

**Comment by benediktkaiser** [comment]
"Nobody cares about it only you"  ~ Maga
